FROM rails:latest
MAINTAINER Dima Rogov <navydimka@gmail.com>

RUN mkdir /rails-app
WORKDIR /rails-app

RUN locale-gen en_US.UTF-8 
ENV LANG en_US.UTF-8 
ENV LANGUAGE en_US:en 
ENV LC_ALL en_US.UTF-8

COPY . /rails-app
RUN bundle install

ENV RAILS_ENV production

CMD bundle exec puma -C config/puma.rb
