version: '2'
services:
  db:
    image: postgres
    container_name: thinknetica-postgres
  web:
    build: .
    container_name: thinknetica-rails
    command: bash -c "bundle install &&  bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - /Code/dev/Thinknetica-RailsApp/rails-manager:/rails-app
    ports:
      - "3000:3000"
    depends_on:
      - db
